version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always

  app:
    build: ./app
    ports:
      - "80:80"
    restart: always
