version: "3.9"

services:
  api:
    image: yourusername/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always

  app:
    image: yourusername/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
